//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_64396
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Bt book.
    /// </summary>
    // *** Start programmer edit section *** (BtBook CustomAttributes)

    // *** End programmer edit section *** (BtBook CustomAttributes)
    [AutoAltered()]
    [Caption("Bt book")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BtBookE", new string[] {
            "Book as \'Book\'",
            "Book.Title as \'Title\'"}, Hidden=new string[] {
            "Book.Title"})]
    [MasterViewDefineAttribute("BtBookE", "Book", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Title")]
    [View("BtBookL", new string[] {
            "Book.Title as \'Title\'"})]
    public class BtBook : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Product_64396.Book fBook;
        
        // *** Start programmer edit section *** (BtBook CustomMembers)

        // *** End programmer edit section *** (BtBook CustomMembers)

        
        /// <summary>
        /// Bt book.
        /// </summary>
        // *** Start programmer edit section *** (BtBook.Book CustomAttributes)

        // *** End programmer edit section *** (BtBook.Book CustomAttributes)
        [PropertyStorage(new string[] {
                "Book"})]
        public virtual IIS.Product_64396.Book Book
        {
            get
            {
                // *** Start programmer edit section *** (BtBook.Book Get start)

                // *** End programmer edit section *** (BtBook.Book Get start)
                IIS.Product_64396.Book result = this.fBook;
                // *** Start programmer edit section *** (BtBook.Book Get end)

                // *** End programmer edit section *** (BtBook.Book Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BtBook.Book Set start)

                // *** End programmer edit section *** (BtBook.Book Set start)
                this.fBook = value;
                // *** Start programmer edit section *** (BtBook.Book Set end)

                // *** End programmer edit section *** (BtBook.Book Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "BtBookE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BtBookE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BtBookE", typeof(IIS.Product_64396.BtBook));
                }
            }
            
            /// <summary>
            /// "BtBookL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BtBookL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BtBookL", typeof(IIS.Product_64396.BtBook));
                }
            }
        }
    }
}
