//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_64396
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// BtSpeaker.
    /// </summary>
    // *** Start programmer edit section *** (BtSpeaker CustomAttributes)

    // *** End programmer edit section *** (BtSpeaker CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BtSpeakerE", new string[] {
            "Speaker"})]
    [View("BtSpeakerL", new string[] {
            "Speaker.LastName as \'LastName\'",
            "Speaker.FirstName as \'FirstName\'",
            "Speaker.MiddleName as \'MiddleName\'"})]
    public class BtSpeaker : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Product_64396.Speaker fSpeaker;
        
        // *** Start programmer edit section *** (BtSpeaker CustomMembers)

        // *** End programmer edit section *** (BtSpeaker CustomMembers)

        
        /// <summary>
        /// BtSpeaker.
        /// </summary>
        // *** Start programmer edit section *** (BtSpeaker.Speaker CustomAttributes)

        // *** End programmer edit section *** (BtSpeaker.Speaker CustomAttributes)
        [PropertyStorage(new string[] {
                "Speaker"})]
        public virtual IIS.Product_64396.Speaker Speaker
        {
            get
            {
                // *** Start programmer edit section *** (BtSpeaker.Speaker Get start)

                // *** End programmer edit section *** (BtSpeaker.Speaker Get start)
                IIS.Product_64396.Speaker result = this.fSpeaker;
                // *** Start programmer edit section *** (BtSpeaker.Speaker Get end)

                // *** End programmer edit section *** (BtSpeaker.Speaker Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BtSpeaker.Speaker Set start)

                // *** End programmer edit section *** (BtSpeaker.Speaker Set start)
                this.fSpeaker = value;
                // *** Start programmer edit section *** (BtSpeaker.Speaker Set end)

                // *** End programmer edit section *** (BtSpeaker.Speaker Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "BtSpeakerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BtSpeakerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BtSpeakerE", typeof(IIS.Product_64396.BtSpeaker));
                }
            }
            
            /// <summary>
            /// "BtSpeakerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BtSpeakerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BtSpeakerL", typeof(IIS.Product_64396.BtSpeaker));
                }
            }
        }
    }
}
