//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_64396
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Report.
    /// </summary>
    // *** Start programmer edit section *** (Report CustomAttributes)

    // *** End programmer edit section *** (Report CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ReportE", new string[] {
            "ReportDate as \'Report date\'",
            "BookRating as \'Book rating\'",
            "UrlPresentation as \'Url presentation\'",
            "UrlVideo as \'Url video\'",
            "Review as \'Review\'",
            "Book as \'Book\'",
            "Book.Title as \'Title\'",
            "Speaker as \'Speaker\'",
            "Speaker.LastName as \'Last name\'"}, Hidden=new string[] {
            "Book.Title",
            "Speaker.LastName"})]
    [MasterViewDefineAttribute("ReportE", "Book", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Title")]
    [MasterViewDefineAttribute("ReportE", "Speaker", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "LastName")]
    public class Report : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fReportDate;
        
        private int fBookRating;
        
        private string fUrlPresentation;
        
        private string fUrlVideo;
        
        private string fReview;
        
        private IIS.Product_64396.Book fBook;
        
        private IIS.Product_64396.Speaker fSpeaker;
        
        private IIS.Product_64396.ClubMeeting fClubMeeting;
        
        // *** Start programmer edit section *** (Report CustomMembers)

        // *** End programmer edit section *** (Report CustomMembers)

        
        /// <summary>
        /// ReportDate.
        /// </summary>
        // *** Start programmer edit section *** (Report.ReportDate CustomAttributes)

        // *** End programmer edit section *** (Report.ReportDate CustomAttributes)
        public virtual System.DateTime ReportDate
        {
            get
            {
                // *** Start programmer edit section *** (Report.ReportDate Get start)

                // *** End programmer edit section *** (Report.ReportDate Get start)
                System.DateTime result = this.fReportDate;
                // *** Start programmer edit section *** (Report.ReportDate Get end)

                // *** End programmer edit section *** (Report.ReportDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Report.ReportDate Set start)

                // *** End programmer edit section *** (Report.ReportDate Set start)
                this.fReportDate = value;
                // *** Start programmer edit section *** (Report.ReportDate Set end)

                // *** End programmer edit section *** (Report.ReportDate Set end)
            }
        }
        
        /// <summary>
        /// BookRating.
        /// </summary>
        // *** Start programmer edit section *** (Report.BookRating CustomAttributes)

        // *** End programmer edit section *** (Report.BookRating CustomAttributes)
        public virtual int BookRating
        {
            get
            {
                // *** Start programmer edit section *** (Report.BookRating Get start)

                // *** End programmer edit section *** (Report.BookRating Get start)
                int result = this.fBookRating;
                // *** Start programmer edit section *** (Report.BookRating Get end)

                // *** End programmer edit section *** (Report.BookRating Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Report.BookRating Set start)

                // *** End programmer edit section *** (Report.BookRating Set start)
                this.fBookRating = value;
                // *** Start programmer edit section *** (Report.BookRating Set end)

                // *** End programmer edit section *** (Report.BookRating Set end)
            }
        }
        
        /// <summary>
        /// UrlPresentation.
        /// </summary>
        // *** Start programmer edit section *** (Report.UrlPresentation CustomAttributes)

        // *** End programmer edit section *** (Report.UrlPresentation CustomAttributes)
        [StrLen(255)]
        public virtual string UrlPresentation
        {
            get
            {
                // *** Start programmer edit section *** (Report.UrlPresentation Get start)

                // *** End programmer edit section *** (Report.UrlPresentation Get start)
                string result = this.fUrlPresentation;
                // *** Start programmer edit section *** (Report.UrlPresentation Get end)

                // *** End programmer edit section *** (Report.UrlPresentation Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Report.UrlPresentation Set start)

                // *** End programmer edit section *** (Report.UrlPresentation Set start)
                this.fUrlPresentation = value;
                // *** Start programmer edit section *** (Report.UrlPresentation Set end)

                // *** End programmer edit section *** (Report.UrlPresentation Set end)
            }
        }
        
        /// <summary>
        /// UrlVideo.
        /// </summary>
        // *** Start programmer edit section *** (Report.UrlVideo CustomAttributes)

        // *** End programmer edit section *** (Report.UrlVideo CustomAttributes)
        [StrLen(255)]
        public virtual string UrlVideo
        {
            get
            {
                // *** Start programmer edit section *** (Report.UrlVideo Get start)

                // *** End programmer edit section *** (Report.UrlVideo Get start)
                string result = this.fUrlVideo;
                // *** Start programmer edit section *** (Report.UrlVideo Get end)

                // *** End programmer edit section *** (Report.UrlVideo Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Report.UrlVideo Set start)

                // *** End programmer edit section *** (Report.UrlVideo Set start)
                this.fUrlVideo = value;
                // *** Start programmer edit section *** (Report.UrlVideo Set end)

                // *** End programmer edit section *** (Report.UrlVideo Set end)
            }
        }
        
        /// <summary>
        /// Review.
        /// </summary>
        // *** Start programmer edit section *** (Report.Review CustomAttributes)

        // *** End programmer edit section *** (Report.Review CustomAttributes)
        [StrLen(255)]
        public virtual string Review
        {
            get
            {
                // *** Start programmer edit section *** (Report.Review Get start)

                // *** End programmer edit section *** (Report.Review Get start)
                string result = this.fReview;
                // *** Start programmer edit section *** (Report.Review Get end)

                // *** End programmer edit section *** (Report.Review Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Report.Review Set start)

                // *** End programmer edit section *** (Report.Review Set start)
                this.fReview = value;
                // *** Start programmer edit section *** (Report.Review Set end)

                // *** End programmer edit section *** (Report.Review Set end)
            }
        }
        
        /// <summary>
        /// Report.
        /// </summary>
        // *** Start programmer edit section *** (Report.Book CustomAttributes)

        // *** End programmer edit section *** (Report.Book CustomAttributes)
        [PropertyStorage(new string[] {
                "Book"})]
        [NotNull()]
        public virtual IIS.Product_64396.Book Book
        {
            get
            {
                // *** Start programmer edit section *** (Report.Book Get start)

                // *** End programmer edit section *** (Report.Book Get start)
                IIS.Product_64396.Book result = this.fBook;
                // *** Start programmer edit section *** (Report.Book Get end)

                // *** End programmer edit section *** (Report.Book Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Report.Book Set start)

                // *** End programmer edit section *** (Report.Book Set start)
                this.fBook = value;
                // *** Start programmer edit section *** (Report.Book Set end)

                // *** End programmer edit section *** (Report.Book Set end)
            }
        }
        
        /// <summary>
        /// Report.
        /// </summary>
        // *** Start programmer edit section *** (Report.Speaker CustomAttributes)

        // *** End programmer edit section *** (Report.Speaker CustomAttributes)
        [PropertyStorage(new string[] {
                "Speaker"})]
        [NotNull()]
        public virtual IIS.Product_64396.Speaker Speaker
        {
            get
            {
                // *** Start programmer edit section *** (Report.Speaker Get start)

                // *** End programmer edit section *** (Report.Speaker Get start)
                IIS.Product_64396.Speaker result = this.fSpeaker;
                // *** Start programmer edit section *** (Report.Speaker Get end)

                // *** End programmer edit section *** (Report.Speaker Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Report.Speaker Set start)

                // *** End programmer edit section *** (Report.Speaker Set start)
                this.fSpeaker = value;
                // *** Start programmer edit section *** (Report.Speaker Set end)

                // *** End programmer edit section *** (Report.Speaker Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Product_64396.ClubMeeting.
        /// </summary>
        // *** Start programmer edit section *** (Report.ClubMeeting CustomAttributes)

        // *** End programmer edit section *** (Report.ClubMeeting CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ClubMeeting"})]
        public virtual IIS.Product_64396.ClubMeeting ClubMeeting
        {
            get
            {
                // *** Start programmer edit section *** (Report.ClubMeeting Get start)

                // *** End programmer edit section *** (Report.ClubMeeting Get start)
                IIS.Product_64396.ClubMeeting result = this.fClubMeeting;
                // *** Start programmer edit section *** (Report.ClubMeeting Get end)

                // *** End programmer edit section *** (Report.ClubMeeting Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Report.ClubMeeting Set start)

                // *** End programmer edit section *** (Report.ClubMeeting Set start)
                this.fClubMeeting = value;
                // *** Start programmer edit section *** (Report.ClubMeeting Set end)

                // *** End programmer edit section *** (Report.ClubMeeting Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ReportE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ReportE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ReportE", typeof(IIS.Product_64396.Report));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Report.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfReport CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfReport CustomAttributes)
    public class DetailArrayOfReport : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Product_64396.DetailArrayOfReport members)

        // *** End programmer edit section *** (IIS.Product_64396.DetailArrayOfReport members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Report by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Report.
        /// </summary>
        public DetailArrayOfReport(IIS.Product_64396.ClubMeeting fClubMeeting) : 
                base(typeof(Report), ((ICSSoft.STORMNET.DataObject)(fClubMeeting)))
        {
        }
        
        public IIS.Product_64396.Report this[int index]
        {
            get
            {
                return ((IIS.Product_64396.Report)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Product_64396.Report dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
