//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_64396
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// BookBS.
    /// </summary>
    // *** Start programmer edit section *** (BookBS CustomAttributes)

    // *** End programmer edit section *** (BookBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class BookBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (BookBS CustomMembers)

        // *** End programmer edit section *** (BookBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateBook CustomAttributes)

        // *** End programmer edit section *** (OnUpdateBook CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateBook(IIS.Product_64396.Book UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateBook)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateBook)
        }
    }
}
