//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_64396
{
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// SpeakerBS.
    /// </summary>
    // *** Start programmer edit section *** (SpeakerBS CustomAttributes)

    // *** End programmer edit section *** (SpeakerBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class SpeakerBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (SpeakerBS CustomMembers)

        // *** End programmer edit section *** (SpeakerBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateSpeaker CustomAttributes)

        // *** End programmer edit section *** (OnUpdateSpeaker CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateSpeaker(IIS.Product_64396.Speaker UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateSpeaker)
            DataObject[] result = new DataObject[0];

            CreateBtSpeaker(UpdatedObject);

            return result;
            // *** End programmer edit section *** (OnUpdateSpeaker)
        }

        public static void CreateBtSpeaker(IIS.Product_64396.Speaker speaker)
        {
            try
            {

                BtSpeaker newInvoice = new BtSpeaker
                {
                   Speaker = speaker

                };


                ICSSoft.STORMNET.DataObject saveObj = (DataObject)newInvoice;
                DataServiceProvider.DataService.UpdateObject(saveObj);
            }
            catch
            {
                Console.WriteLine("Received an error while creating an Invoice object");
            }
        }
    }
}
